name: 'lint'

on: [push, release, pull_request]

jobs:
    release:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout to branch
              uses: actions/checkout@v2

            - name: Setup node.js
              uses: actions/setup-node@v1
              with:
                  node-version: 14.x

            - name: Install packages
              run: npm install

            - name: Lint code
              run: yarn lint
