name: 'cd'

on:
    push:
        branches:
            - release

jobs:
    cd:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout to branch
              uses: actions/checkout@v2

            - name: Setup node.js
              uses: actions/setup-node@v1
              with:
                  node-version: 14.x

            - name: Install packages
              run: npm install

            - name: Calculate version
              id: calculateVersion
              run: |
                  APP_VERSION=`cat package.json | jq ".version" -M | sed 's/\"//g'`
                  echo "::set-output name=AppVersion::$APP_VERSION"
                  echo "app version = v$APP_VERSION"

            - name: Build VSIX package
              run: npx vsce package

            - name: Publish extension package
              env:
                  VSCODE_MARKETPLACE_TOKEN: ${{ secrets.VSCODE_MARKETPLACE_TOKEN }}
              run: npx vsce publish -p $VSCODE_MARKETPLACE_TOKEN

            - uses: actions/upload-artifact@v2
              name: Upload artifact
              with:
                  name: custom-profiles-for-vscode.v${{ steps.calculateVersion.outputs.AppVersion }}.vsix
                  path: custom-profiles-for-vscode.v${{ steps.calculateVersion.outputs.AppVersion }}.vsix
